; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Common settings shared by both environments
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit SSD1306
	adafruit/Adafruit GFX Library
	knolleary/PubSubClient

; USB Upload via COM3
[env:esp32dev-usb]
upload_port = COM3
monitor_port = COM3

; OTA Upload via network (change IP to match your ESP32)
[env:esp32dev-ota]
upload_protocol = espota
upload_port = 192.168.4.42
upload_flags = 
	--auth=
	--port=3232
